
const keyMap = [
    {letter: 'q', name: 'name', src: 'Heater1.mp3'},
    {letter: 'w', name: 'name', src: 'wilhelm2.mp3'},
    {letter: 'e', name: 'name', src: 'bullfrog.mp3'},
    {letter: 'r', name: 'name', src: 'martian-gun.mp3'},
    {letter: 't', name: 'name', src: 'badumttss.mp3'},
    {letter: 'y', name: 'name', src: 'nani.mp3'},
    {letter: 'u', name: 'name', src: 'Heater1.mp3'},
    {letter: 'i', name: 'name', src: 'iphone.mp3'},
    {letter: 'o', name: 'name', src: 'airhorn.mp3'},
    {letter: 'p', name: 'name', src: 'zw.mp3'},
    {letter: 'a', name: 'name', src: 'goes-without-saying.mp3'},
    {letter: 's', name: 'name', src: 'th.mp3'},
    {letter: 'd', name: 'name', src: 'thehand.mp3'},
    {letter: 'f', name: 'name', src: 'facebook2.mp3'},
    {letter: 'g', name: 'name', src: 'oof2.mp3'},
    {letter: 'h', name: 'name', src: 'mariojump2.mp3'},
    {letter: 'j', name: 'name', src: 'kaching.mp3'},
    {letter: 'k', name: 'name', src: 'clapping.mp3'},
    {letter: 'l', name: 'name', src: 'dialup.mp3'},
    {letter: ';', name: 'name', src: 'discord.mp3'},
    {letter: 'z', name: 'name', src: 'plucky.mp3'},
    {letter: 'x', name: 'name', src: 'xfiles.mp3'},
    {letter: 'c', name: 'name', src: 'nflix.mp3'},
    {letter: 'v', name: 'name', src: 'mgs.mp3'},
    {letter: 'b', name: 'name', src: 'jnboi.mp3'},
    {letter: 'n', name: 'name', src: 'hollow.mp3'},
    {letter: 'm', name: 'name', src: 'nani3.mp3'},
    {letter: ',', name: 'name', src: 'sonyPlaystation.mp3'},
    {letter: '.', name: 'name', src: 'discord.mp3'},
    {letter: '/', name: 'name', src: 'discord.mp3'},
]
export default keyMap